; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:crowpanel_advance_3_5]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_CONF_PATH=lv_conf.h
	-I.
	-Iinclude

# Libraries used by the project
lib_deps =
	OneWire
	milesburton/DallasTemperature
	https://github.com/adafruit/Adafruit_SHT4X.git
	https://github.com/adafruit/Adafruit_BusIO.git
	WiFi
	arduino-libraries/ArduinoHttpClient
	lovyan03/LovyanGFX
	lvgl/lvgl@^8.3.11
	https://github.com/TAMCTec/gt911-arduino.git
